language: ruby
cache: bundler

sudo: required
dist: trusty

rvm:
  - 2.4.0

before_install:
    - gem update --system
    - gem install bundler

install:
  - gem install rails
  - bundle install

jobs:
 include:
   - stage: Test
     script:
     - rake features

env:
 global:
   - CI_NODE_TOTAL=1
 matrix:
   - CI_NODE_INDEX=0

branches:
  only:
    - master

notifications:
  email:
    - hendri.antomy@mokapos.com
