language: ruby
cache: bundler

sudo: required
dist: trusty
group: deprecated-2017Q4

rvm:
  - 2.4.0

before_install:
  - gem update --system
  - gem --version
install: gem install rails

before_script:
#  - 'sudo cp Root-R1.crt /usr/local/share/ca-certificates/Root-R1.crt'
#  - 'sudo update-ca-certificates'
#  - 'curl -k https://dev.mokapos.com'
  - './count_feature.sh'
  - 'sh time_param.sh'
  - 'export TZ=Asia/Jakarta'
  - 'date'
  # download and extract
  - 'mkdir joss'
  - 'cd joss'
  - 'wget https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz'
  - 'tar xf sc-4.4.12-linux.tar.gz'
  - 'ls'
  - 'cd ..'
  - 'sudo mv joss/sc-4.4.12-linux/bin/sc /usr/local/bin/sc'
  - 'export PATH=$PATH:/usr/local/bin/sc'
  - 'source ~/.bashrc'
  - 'echo $PATH'
  - 'bundle update'
  - 'bundle install'
  - 'rake db:migrate'
script:
 - bundle exec rake knapsack:cucumber

jobs:
 allow_failures:
   - rvm: 2.4.0
 include:
   - stage: push notif
     script:
     - cucumber features/

env:
 global:
   - CI_NODE_TOTAL=5
 matrix:
   - CI_NODE_INDEX=0
   - CI_NODE_INDEX=1
   - CI_NODE_INDEX=2
   - CI_NODE_INDEX=3
   - CI_NODE_INDEX=4

branches:
  only:
    - master

notifications:
  email:
    - hendri.antomy@mokapos.com
