language: ruby
cache: bundler

sudo: required
dist: trusty

rvm:
  - 2.4.0

addons:
  chrome: stable

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle install

jobs:
  allow_failures:
    - rvm: 2.4.0
  include:
    - stage: push notif
      script:
        - bundle exec rake features

env:
  global:
    - CI_NODE_TOTAL=1
  matrix:
    - CI_NODE_INDEX=0

branches:
  only:
    - master

notifications:
  email:
    - hendri.antomy@mokapos.com