language: ruby
cache: bundler

sudo: required
dist: trusty
group: deprecated-2017Q4

rvm:
  - 2.4.0

addons:
  chrome: stable

before_install:
    - gem update --system
    - gem install bundler

#install: gem install rails

before_script:
# - 'export PATH=$PATH:/usr/local/bin/sc'
#  - 'source ~/.bashrc'
#  - 'echo $PATH'
#  - 'bundle update'
  - 'bundle install'
  - 'sudo gem install cucumber'
#script:
# - bundle exec rake knapsack:cucumber

jobs:
 allow_failures:
   - rvm: 2.4.0
 include:
   - stage: push notif
     script:
     - cucumber features/

env:
 global:
   - CI_NODE_TOTAL=1
 matrix:
   - CI_NODE_INDEX=0

branches:
  only:
    - master

notifications:
  email:
    - hendri.antomy@mokapos.com
